name: ci-wf
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Craete Package.jason
        run: npm init -y
      - name: Install HTML Hint
        run: npm install --save-dev htmlhint
      - name: Run htmlhint
        run: npx htmlhint "**/*.html"